name: Convert to M3U8
   on:
     workflow_dispatch:
     schedule:
       - cron: '0 * * * *'  # يُحدث الملف كل ساعة

   jobs:
     convert:
       runs-on: ubuntu-latest
       steps:
         - name: Fetch M3U
           run: |
             wget "http://wanicelife.com:8880/get.php?username=D12m3967&password=74185011&type=m3u_plus" -O playlist.m3u
             sed -i 's|http.*\.m3u8|https://shls-mbcbollywood-prod-dub.shahid.net/out/v1/xxx/index.m3u8|g' playlist.m3u
             mv playlist.m3u playlist.m3u8
         - name: Upload to GitHub
           uses: actions/upload-artifact@v2
           with:
             name: playlist.m3u8
             path: playlist.m3u8
